### ISSUE TITLE
Please expose MySQLError internals

### ISSUE THREAD

**Issue by jberryman** [paul-rouse/mysql#24]
I don't see a way to handle specific mysql exceptions without access to internals or helper functions (e.g. for `errNumber`.

**Comment by paul-rouse** [comment]
We already have `mysql_errno` and `mysql_error` available from Database.MySQL.Base.C - do you need something else?

**Comment by paul-rouse** [comment]
Actually, that's probably too low level - but MySQLError exposes `errFunction`, `errNumber` and `errMessage` field names.

**Comment by jberryman** [comment]
> but MySQLError exposes errFunction, errNumber and errMessage field names.

Oh you're right, but they don't show up in the haddocks for some reason and so I must have misinterpreted what was happening. Thanks!

**Comment by paul-rouse** [comment]
I think they don't show up because the actual constructors are hidden - I'll see if I can clarify the documentation by hand!
