### ISSUE TITLE
Support JSON type?

### ISSUE THREAD

**Issue by ryota-ka** [paul-rouse/mysql#35]
When I tried to retrieve records from a table which has a column of JSON type, I've got an error `unknown field type 245`.
Should we update `Database.MySQL.Base.Type.Type` and `toType` function?

**Comment by paul-rouse** [comment]
Sorry for the delay replying.  I cannot see any problem with this, if you would like do a PR.

**Comment by ryota-ka** [comment]
Okay, I'll send a pull request later!
