### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by jasonsychau** [paul-rouse/mysql#38]
Is anybody familiar with this error?

--  While building package mysql-0.1.7 using:
      /tmp/stack25371/mysql-0.1.7/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 configure --user --package-db=clear --package-db=global --package-db=/home/<USERNAME>/.stack/snapshots/x86_64-linux/ef05213cc7cbe827098f5cfbce19daa0d6eb0b7be5d82654ae3f4172681bea57/8.6.5/pkgdb --libdir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/ef05213cc7cbe827098f5cfbce19daa0d6eb0b7be5d82654ae3f4172681bea57/8.6.5/lib --bindir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/ef05213cc7cbe827098f5cfbce19daa0d6eb0b7be5d82654ae3f4172681bea57/8.6.5/bin --datadir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/ef05213cc7cbe827098f5cfbce19daa0d6eb0b7be5d82654ae3f4172681bea57/8.6.5/share --libexecdir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/ef05213cc7cbe827098f5cfbce19daa0d6eb0b7be5d82654ae3f4172681bea57/8.6.5/libexec --sysconfdir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/ef05213cc7cbe827098f5cfbce19daa0d6eb0b7be5d82654ae3f4172681bea57/8.6.5/etc --docdir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/ef05213cc7cbe827098f5cfbce19daa0d6eb0b7be5d82654ae3f4172681bea57/8.6.5/doc/mysql-0.1.7 --htmldir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/ef05213cc7cbe827098f5cfbce19daa0d6eb0b7be5d82654ae3f4172681bea57/8.6.5/doc/mysql-0.1.7 --haddockdir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/ef05213cc7cbe827098f5cfbce19daa0d6eb0b7be5d82654ae3f4172681bea57/8.6.5/doc/mysql-0.1.7 --dependency=Cabal=Cabal-2.4.1.0-3JC906oWQ73Ah7bYkIcI4J --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=containers=containers-0.6.0.1 -f-developer --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1

**Comment by paul-rouse** [comment]
Could you please say what distro you are using, and whether you are building against the standard MySQL client library, and also what Stackage snapshot you are using, and whether you have any extra deps in stack.yaml?

**Comment by jasonsychau** [comment]
These are in my stack.yaml

distro: NixOS,
snapshot: lts-16.13
extra-deps: json-0.10, conduit-1.3.1.1, hspec-2.7.4, QuickCheck-2.13.2

and I get this error:

```
--  While building package mysql-0.1.7 using:
      /tmp/stack4580/mysql-0.1.7/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-3.0.1.0 configure --user --package-db=clear --package-db=global --package-db=/home/<USERNAME>/.stack/snapshots/x86_64-linux/bf5e6c98ebab71ee04f7301e97ff0b5261616a02eeabe8860c6699c69fb5d353/8.8.4/pkgdb --libdir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/bf5e6c98ebab71ee04f7301e97ff0b5261616a02eeabe8860c6699c69fb5d353/8.8.4/lib --bindir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/bf5e6c98ebab71ee04f7301e97ff0b5261616a02eeabe8860c6699c69fb5d353/8.8.4/bin --datadir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/bf5e6c98ebab71ee04f7301e97ff0b5261616a02eeabe8860c6699c69fb5d353/8.8.4/share --libexecdir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/bf5e6c98ebab71ee04f7301e97ff0b5261616a02eeabe8860c6699c69fb5d353/8.8.4/libexec --sysconfdir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/bf5e6c98ebab71ee04f7301e97ff0b5261616a02eeabe8860c6699c69fb5d353/8.8.4/etc --docdir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/bf5e6c98ebab71ee04f7301e97ff0b5261616a02eeabe8860c6699c69fb5d353/8.8.4/doc/mysql-0.1.7 --htmldir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/bf5e6c98ebab71ee04f7301e97ff0b5261616a02eeabe8860c6699c69fb5d353/8.8.4/doc/mysql-0.1.7 --haddockdir=/home/<USERNAME>/.stack/snapshots/x86_64-linux/bf5e6c98ebab71ee04f7301e97ff0b5261616a02eeabe8860c6699c69fb5d353/8.8.4/doc/mysql-0.1.7 --dependency=Cabal=Cabal-3.0.1.0 --dependency=base=base-4.13.0.0 --dependency=bytestring=bytestring-0.10.10.1 --dependency=containers=containers-0.6.2.1 -f-developer --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1
```

I don't know how to answer "building against the standard MySQL client library".

**Comment by paul-rouse** [comment]
The question about the client library was whether you have your distro's client package for MySQL installed, or MariaDB.  You need one of them, and the `setup` program needs to be able to find the command to report the configuration under one of the names `mysql_config`, `mysql_config5` or `mariadb_config`.

**Comment by jasonsychau** [comment]
Okay, I'll check this.

**Comment by jasonsychau** [comment]
I fixed by installing a mysql library.

**Comment by paul-rouse** [comment]
Great!
