### ISSUE TITLE
Setup.hs should call `mysql_config --libs_sys'

### ISSUE THREAD

**Issue by pjones** [paul-rouse/mysql#39]
When building a static executable on Linux, the final link phase will bring in `libmariadbclient.a` *before* system libraries such as `libssl.a`.  This leads to a ton of undefined symbols.

There's a flag to `mysql_config` called `--libs_sys` (at least in mariadb) that returns the system libraries that must be linked prior to mariadb.

Is there any reason we shouldn't be using that flag?  If there are no objections I can submit a PR.

For others who find this, I worked around this by placing the following script in `/usr/bin/mysql_config` on an Alpine Linux Docker image:

```sh
if [ $# -gt 0 ] && [ "$1" = "--libs" ]; then
  echo "$(mariadb_config --libs_sys)" "$(mariadb_config --libs)"
else
  mariadb_config "$@"
fi
```

Then in my `*.cabal` file:

```cabal
ld-options:      -static -pthread
extra-libraries:
  z
  ssl
  crypto
  mariadb
```

NOTE: This additional entry in the `Dockerfile` is required:

```Dockerfile
RUN cd /usr/lib \
 && ln -s libmariadbclient.a libmariadb.a
```

**Comment by paul-rouse** [comment]
Yes, a PR would be welcome!  However, as far as I can see, no version of `mysql_config` supports this option, and I believe older versions of `mariadb_config` don't either.  So appropriate conditionals will be required.
