### ISSUE TITLE
Hackage docs

### ISSUE THREAD

**Issue by danwdart** [paul-rouse/mysql#43]
Hey, can't find any Hackage docs, so having to peruse the source. Are there any plans to add any or has that process been halted accidentally?

**Comment by sjakobi** [comment]
The automatic doc builds are failing because the build machine doesn't appear to have the `mysqlclient` library: https://hackage.haskell.org/package/mysql-0.2.1/reports/2

**Comment by paul-rouse** [comment]
Yes, it's a pain.  Stackage has no problem building them: https://www.stackage.org/package/mysql
I'll try to build and upload them as part of the source distribution process.
